namespace HotfixMods.Core.Flags.Db2
{
    [Flags]
    public enum ItemDisplayInfoFlags : long
    {
        DEFAULT = 0,
        EMBLAZONED_TABARD_COMMON = 1,
        NO_SHEATHED_KIT_FOR_SPELL_COMBAT_ANIM = 2,
        HIDE_PANTS_AND_BELT = 4,
        EMBLAZONED_TABARD_RARE = 8,
        EMBLAZONED_TABARD_EPIC = 16,
        USE_SPEAR_RANGED_WEAPON_ATTACHMENT = 32,
        INHERIT_CHARACTER_ANIMATION = 64,
        MIRROR_ANIMATION_RIGHT_SHOULDER_TO_LEFT = 128,
        MIRROR_MODEL_IN_OFF_HAND = 256,
        DISABLE_TABARD_FROM_WAIST = 512,
        MIRROR_MODEL_IN_MAIN_HAND = 1024,
        MIRROR_WARGLAIVE_ON_SHEATHED = 2048,
        FLIP_MODEL_ON_SHEATHED = 4096,
        USE_ALTERNATE_WEAPON_TRAIL_ENDPOINTS = 8192,
        FORCE_SHEATHED = 16384,
        DONT_CLOSE_HANDS = 32768,
        UNSHEATHED_FOR_SPELL_ANIM = 65536,
        BREWMASTER_UNSHEATHED = 131072,
        HIDE_BELT_BUCKLE = 262144,
        NO_DEFAULT_BOW_STRING = 524288
    }
}
