using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HotfixMods.Core.Enums
{
    public enum ItemStatType : long
    {
        NONE = -1,
        MANA = 0,
        HEALTH = 1,
        UNK_2 = 2,
        AGILITY = 3,
        STRENGTH = 4,
        INTELLECT = 5,
        UNK_6 = 6,
        STAMINA = 7,
        UNK_8 = 8,
        UNK_9 = 9,
        UNK_10 = 10,
        UNK_11 = 11,
        DEFENSE = 12,
        DODGE = 13,
        PARRY = 14,
        BLOCK = 15,
        HIT_MELEE = 16,
        HIT_RANGED = 17,
        HIT_SPELL = 18,
        CRITICAL_STRIKE_MELEE = 19,
        CRITICAL_STRIKE_RANGED = 20,
        CRITICAL_STRIKE_SPELL = 21,
        CORRUPTION = 22,
        CORRUPTION_RESISTANCE = 23,
        RANDOM_STAT_1 = 24,
        RANDOM_STAT_2 = 25,
        CRITICAL_STRIKE_AVOIDANCE_RANGED = 26,
        CRITICAL_STRIKE_AVOIDANCE_SPELL = 27,
        UNK_28 = 28,
        UNK_29 = 29,
        UNK_30 = 30,
        HIT = 31,
        CRITICAL_STRIKE = 32,
        HIT_AVOIDANCE = 33,
        CRITICAL_STRIKE_AVOIDANCE = 34,
        PVP_RESILIENCE = 35,
        HASTE = 36,
        EXPERTISE = 37,
        ATTACK_POWER = 38,
        RANGED_ATTACK_POWER = 39,
        VERSATILITY = 40,
        BONUS_HEALING = 41,
        BONUS_DAMAGE = 42,
        MANA_REGENERATION = 43,
        ARMOR_PENETRATION = 44,
        SPELL_POWER = 45,
        HEALTH_PER_5_SEC = 46,
        SPELL_PENETRATION = 47,
        BLOCK_VALUE = 48,
        MASTERY = 49,
        BONUS_ARMOR = 50,
        FIRE_RESISTANCE = 51,
        FROST_RESISTANCE = 52,
        HOLY_RESISTANCE = 53,
        SHADOW_RESISTANCE = 54,
        NATURE_RESISTANCE = 55,
        ARCANE_RESISTANCE = 56,
        PVP_POWER = 57,
        UNK_58 = 58,
        UNK_59 = 59,
        UNK_60 = 60,
        SPEED = 61,
        LEECH = 62,
        AVOIDANCE = 63,
        INDESTRUCTIBLE = 64,
        UNUSED_7 = 65,
        UNK_66 = 66,
        VERSATILITY_UNUSED = 67, // Duplicate Versatility - is this unused?
        UNUSED_10 = 68,
        UNUSED_11 = 69,
        UNUSED_12 = 70,
        INTELLECT_AGILITY_STRENGTH = 71,
        AGILITY_STRENGTH = 72,
        INTELLECT_AGILITY = 73,
        INTELLECT_STRENGTH = 74
    }
}
