namespace HotfixMods.Core.Enums.Db2
{
    // ChrModel table
    public enum ChrModelId
    {
        DEFAULT = 0,

        HUMAN_MALE = 1,
        HUMAN_FEMALE = 2,
        ORC_MALE = 3,
        ORC_FEMALE = 4,
        DWARF_MALE = 5,
        DWARF_FEMALE = 6,
        NIGHT_ELF_MALE = 7,
        NIGHT_ELF_FEMALE = 8,
        SCOURGE_MALE = 9,
        SCOURGE_FEMALE = 10,
        TAUREN_MALE = 11,
        TAUREN_FEMALE = 12,
        GNOME_MALE = 13,
        GNOME_FEMALE = 14,
        TROLL_MALE = 15,
        TROLL_FEMALE = 16,
        GOBLIN_MALE = 17,
        GOBLIN_FEMALE = 18,
        BLOOD_ELF_MALE = 19,
        BLOOD_ELF_FEMALE = 20,
        DRAENEI_MALE = 21,
        DRAENEI_FEMALE = 22,
        FEL_ORC_MALE = 23,
        FEL_ORC_FEMALE = 24,
        NAGA_MALE = 25,
        NAGA_FEMALE = 26,
        BROKEN_MALE = 27,
        BROKEN_FEMALE = 28,
        SKELETON_MALE = 29,
        SKELETON_FEMALE = 30,
        VRYKUL_MALE = 31,
        VRYKUL_FEMALE = 32,
        TUSKARR_MALE = 33,
        TUSKARR_FEMALE = 34,
        FOREST_TROLL_MALE = 35,
        FOREST_TROLL_FEMALE = 36,
        TAUNKA_MALE = 37,
        TAUNKA_FEMALE = 38,
        NORTHREND_SKELETON_MALE = 39,
        NORTHREND_SKELETON_FEMALE = 40,
        ICE_TROLL_MALE = 41,
        ICE_TROLL_FEMALE = 42,
        WORGEN_MALE = 43,
        WORGEN_FEMALE = 44,
        GILNEAN_MALE = 45,
        GILNEAN_FEMALE = 46,
        PANDAREN_MALE = 47,
        PANDAREN_FEMALE = 48,

        NIGHTBORNE_MALE = 53,
        NIGHTBORNE_FEMALE = 54,
        HIGHMOUNTAIN_TAUREN_MALE = 55,
        HIGHMOUNTAIN_TAUREN_FEMALE = 56,
        VOID_ELF_MALE = 57,
        VOID_ELF_FEMALE = 58,
        LIGHTFORGED_DRAENEI_MALE = 59,
        LIGHTFORGED_DRAENEI_FEMALE = 60,
        ZANDALARI_MALE = 61,
        ZANDALARI_FEMALE = 62,
        KUL_TIRAN_MALE = 63,
        KUL_TIRAN_FEMALE = 64,
        THIN_HUMAN_MALE = 65,
        THIN_HUMAN_FEMALE = 66,
        DARK_IRON_DWARF_MALE = 67,
        DARK_IRON_DWARF_FEMALE = 68,
        VULPERA_MALE = 69,
        VULPERA_FEMALE = 70,
        MAGHAR_ORC_MALE = 71,
        MAGHAR_ORC_FEMALE = 72,
        MECHAGNOME_MALE = 73,
        MECHAGNOME_FEMALE = 74,

        DRACTHYR_DRAGON = 89,

        COMPANION_DRAKE = 123,
        COMPANION_PROTODRAGON = 124,
        COMPANION_SERPENT = 125,
        COMPANION_WYVERN = 126,
        DRACTHYR_VISAGE_MALE = 127,
        DRACTHYR_VISAGE_FEMALE = 128,
        COMPANION_PTERRODAX = 129,
    }

}
