namespace HotfixMods.Core.Enums.Db2
{
    // ChrRaces table
    public enum ChrRaceId : sbyte
    {
        DEFAULT = 0,
        HUMAN = 1,
        ORC = 2,
        DWARF = 3,
        NIGHT_ELF = 4,
        SCOURGE = 5,
        TAUREN = 6,
        GNOME = 7,
        TROLL = 8,
        GOBLIN = 9,
        BLOOD_ELF = 10,
        DRAENEI = 11,
        FEL_ORC = 12,
        NAGA = 13,
        BROKEN = 14,
        SKELETON = 15,
        VRYKUL = 16,
        TUSKARR = 17,
        FOREST_TROLL = 18,
        TAUNKA = 19,
        NORTHREND_SKELETON = 20,
        ICE_TROLL = 21,
        WORGEN = 22,
        GILNEAN = 23,
        PANDAREN_NEUTRAL = 24,
        PANDAREN_ALLIANCE = 25,
        PANDAREN_HORDE = 26,
        NIGHTBORNE = 27,
        HIGHMOUNTAIN_TAUREN = 28,
        VOID_ELF = 29,
        LIGHTFORGED_DRAENEI = 30,
        ZANDALARI_TROLL = 31,
        KUL_TIRAN = 32,
        THIN_HUMAN = 33,
        DARK_IRON_DWARF = 34,
        VULPERA = 35,
        MAGHAR_ORC = 36,
        MECHAGNOME = 37,

        DRACTHYR_ALLIANCE = 52,

        DRACTHYR_HORDE = 70,
        COMPANION_DRAKE = 71,
        COMPANION_PROTO_DRAGON = 72,
        COMPANION_SERPENT = 73,
        COMPANION_WYVERN = 74,
        DRACTHYR_VISAGE_ALLIANCE = 75,
        DRACTHYR_VISAGE_HORDE = 76,
        COMPANION_PTERRODAX = 77,
    }
}
