namespace HotfixMods.Core.Enums.Db2
{
    public enum ItemInventoryType
    {
        NON_EQUIPPABLE = 0,
        HEAD = 1,
        NECK = 2,
        SHOULDERS = 3,
        BODY = 4,
        CHEST = 5,
        WAIST = 6,
        LEGS = 7,
        FEET = 8,
        WRISTS = 9,
        HANDS = 10,
        FINGER = 11,
        TRINKET = 12,
        WEAPON = 13,
        SHIELD = 14,
        RANGED = 15,
        CLOAK = 16,
        TWO_HAND_WEAPON = 17,
        BAG = 18,
        TABARD = 19,
        ROBE = 20,
        MAIN_HAND = 21,
        OFF_HAND = 22,
        HOLDABLE = 23,
        AMMO = 24,
        THROWN = 25,
        RANGED_RIGHT = 26,
        QUIVER = 27,
        RELIC = 28,
        PROFESSION_TOOL = 29,
        PROFESSION_GEAR = 30,
        EQUIPABLE_SPELL_OFFENSIVE = 31,
        EQUIPABLE_SPELL_UTILITY = 32,
        EQUIPABLE_SPELL_DEFENSIVE = 33,
        EQUIPABLE_SPELL_MOBILITY = 34,
    }
}
