using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HotfixMods.Core.Flags
{
    [Flags]
    public enum SpellMiscAttributes9 : long
    {
        DEFAULT = 0,
        FORCE_DEST_LOCATION = 1,
        MOD_INVIS_INCLUDES_PARTY = 2,
        ONLY_WHEN_ILLEGALLY_MOUNTED = 4,
        DO_NOT_LOG_AURA_REFRESH = 8,
        MISSILE_SPEED_IS_DELAY_IN_SEC = 16,
        IGNORE_TOTEM_REQUIREMENTS_FOR_CASTING = 32,
        ITEM_CAST_GRANTS_SKILL_GAIN = 64,
        DO_NOT_ADD_TO_UNLEARN_LIST = 128,
        COOLDOWN_IGNORES_RANGED_WEAPON = 256,
        NOT_IN_ARENA = 512,
        TARGET_MUST_BE_GROUNDED = 1024,
        ALLOW_WHILE_BANISHED_AURA_STATE = 2048,
        FACE_UNIT_TARGET_UPON_COMPLETION_OF_JUMP_CHARGE = 4096,
        HASTE_AFFECTS_MELEE_ABILITY_CASTTIME = 8192,
        IGNORE_DEFAULT_RATED_BATTLEGROUND_RESTRICTIONS = 16384,
        DO_NOT_DISPLAY_POWER_COST = 32768,
        NEXT_MODAL_SPELL_REQUIRES_SAME_UNIT_TARGET = 65536,
        AUTOCAST_OFF_BY_DEFAULT = 131072,
        IGNORE_SCHOOL_LOCKOUT = 262144,
        ALLOW_DARK_SIMULACRUM = 524288,
        ALLOW_CAST_WHILE_CHANNELING = 1048576,
        SUPPRESS_VISUAL_KIT_ERRORS = 2097152,
        SPELLCAST_OVERRIDE_IN_SPELLBOOK = 4194304,
        JUMPCHARGE_NO_FACING_CONTROL = 8388608,
        IGNORE_CASTER_HEALING_MODIFIERS = 16777216,
        DO_NOT_CONSUME_CHARGE_IF_ITEM_DELETED = 33554432,
        ITEM_PASSIVE_ON_CLIENT = 67108864,
        FORCE_CORPSE_TARGET = 134217728,
        CANNOT_KILL_TARGET = 268435456,
        LOG_PASSIVE = 536870912,
        NO_MOVEMENT_RADIUS_BONUS = 1073741824,
        CHANNEL_PERSISTS_ON_PET_FOLLOW = 2147483648,
    }
}
